// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGRdZNpaibZEHQz1-SxoLL7NffAyzRhDk',
    appId: '1:107325947565:web:2f7f4d805605b14c521024',
    messagingSenderId: '107325947565',
    projectId: 'partaliste',
    authDomain: 'partaliste.firebaseapp.com',
    storageBucket: 'partaliste.appspot.com',
    measurementId: 'G-FZ8WPJRCRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmzDRmDdRGs9D1reZbnk5FEkSgomhOm_s',
    appId: '1:107325947565:android:925831e46af4b4c8521024',
    messagingSenderId: '107325947565',
    projectId: 'partaliste',
    storageBucket: 'partaliste.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgvZUtMtaeTrKK3cc28Dry9PEJjsONQ2k',
    appId: '1:107325947565:ios:d2dd19f102846402521024',
    messagingSenderId: '107325947565',
    projectId: 'partaliste',
    storageBucket: 'partaliste.appspot.com',
    iosClientId: '107325947565-pf43v7l7jbnbfra0hnta4u3pnid8n898.apps.googleusercontent.com',
    iosBundleId: 'com.neved.partalisteapp',
  );
}
